# Define goal for trigger
#bool is_proccesing
bool cancel
---
# Define the result
geometry_msgs/PoseArray poses
bool success
---
# Define a feedback message
string message
bool success
geometry_msgs/PoseArray poses

